export const errorMessage = "网络请求错误，请稍后重试"
export const successMessage = "操作成功"
export const deleteSuccess = "删除成功"
// export const baseUrl = "https://www.liulongbin.top:8888/api/private/v1/"
export const baseUrl = "http://timemeetyou.com:8889/api/private/v1/"